// @no-cookie-jar
POST https://osu.ppy.sh/session
referer: https://osu.ppy.sh/home
cookie: XSRF-TOKEN=1; osu_session=2%3D
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

_token=1&username=&password=


###


// @no-cookie-jar
GET https://osu.ppy.sh/home



###

// @no-cookie-jar
GET https://osu.ppy.sh/beatmapsets/1151959/download
referer: https://osu.ppy.sh/beatmapsets/1151959
cookie: osu_session=1%3D
